"""Structural types shared between the data pipeline and the RAG indexer."""

from __future__ import annotations

from typing import Protocol


class IndexableDocument(Protocol):
    @property
    def doc_id(self) -> str: ...
    @property
    def doc_type(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def text(self) -> str: ...
    @property
    def source(self) -> str: ...
    @property
    def classification(self) -> str: ...
    @property
    def content_sha256(self) -> str: ...
